apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 80 <- porta do container, se for igual ao port, nao precisa declarar
      nodePort: 30001
  selector:
    app: primeiro-pod
